# Generated by Django 2.0.7 on 2018-07-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='slugs',
        ),
    ]
